// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkY1JsHGwbEC4b5sJIdovEE1KLaYt9Jw',
    appId: '1:224333055970:android:4d46f0ef4313ad2d22dbbb',
    messagingSenderId: '224333055970',
    projectId: 'neveroyatniproketflutter',
    storageBucket: 'neveroyatniproketflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmIbRGCS-Zi7XDhk8Z6YD0QogkUb-tiJ4',
    appId: '1:224333055970:ios:c0ebcf5a3a35a03122dbbb',
    messagingSenderId: '224333055970',
    projectId: 'neveroyatniproketflutter',
    storageBucket: 'neveroyatniproketflutter.firebasestorage.app',
    iosBundleId: 'com.example.nineprakt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmIbRGCS-Zi7XDhk8Z6YD0QogkUb-tiJ4',
    appId: '1:224333055970:ios:c0ebcf5a3a35a03122dbbb',
    messagingSenderId: '224333055970',
    projectId: 'neveroyatniproketflutter',
    storageBucket: 'neveroyatniproketflutter.firebasestorage.app',
    iosBundleId: 'com.example.nineprakt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGkY1JsHGwbEC4b5sJIdovEE1KLaYt9Jw',
    appId: '1:224333055970:web:0c5366ff727de2c522dbbb',
    messagingSenderId: '224333055970',
    projectId: 'neveroyatniproketflutter',
    storageBucket: 'neveroyatniproketflutter.firebasestorage.app',
  );
}
